/**
 * THIS PACKAGE CONTAINS RESOURCE CLASSES FOR IMPLEMENTED CLASS OF METADATASOURCE INTERFACE.
 *
 * @SINCE 1.0
 * @AUTHOR THIRUPATHIREDDY
 * @VERSION 1.1
 */
package com.tvajjala.security.resource;